### ISSUE TITLE
Disabling spawn persistence is a terrible thing

### ISSUE THREAD

**Issue by Lunaphied** [CodeCrafter47/RainbowDev#1]
Spawn chunk persistence may cause many people a huge amount of lag when they build up their spawn. But by disabling it completely, this patch breaks many legitimate uses of the spawn persistence, such as command block systems. 

Maybe make that patch a toggle?

**Comment by CodeCrafter47** [comment]
You can clone the repository, remove the patch from the patches folder and the run build.sh. It will build you a Rainbow.jar with many performance patches but with spawn persistence enabled.
